project:
  type: book
  output-dir: _docs

book:
  title: "Introducción a Unix para Bioinformática"
  author: "David Alberto García Estrada"
  date: "5/24/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  # Information
  site-url: https://github.com/BioCode-Academy
  repo-url: https://github.com/BioCode-Academy/Unix
  sharing: [twitter, facebook, linkedin]
  favicon: images/LogoDavidAlberto.png

bibliography: references.bib

format:
  html:
    logo: images/LogoDavidAlberto.png
    toc-depth: 4
    number-depth: 3

    theme:
      light: cosmo
      dark: darkly
    code-fold: false
    code-copy: true
    freeze: false

editor: visual



